# Generated by Django 5.1.2 on 2024-11-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCobertura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tecnologias', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'area de cobertura',
                'verbose_name_plural': 'areas de cobertura',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('razao_social', models.CharField(max_length=45)),
                ('sede', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('ranking', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAreaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaCobertura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_cobertura_id', to='api.areacobertura')),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_empresa_cnpj', to='api.empresa')),
            ],
            options={
                'verbose_name': 'empresa-area de cobertura',
            },
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('asn', models.CharField(max_length=45)),
                ('ptt', models.CharField(max_length=45)),
                ('bgp', models.CharField(max_length=45)),
                ('operadora_backbone', models.CharField(max_length=45)),
                ('capacidade_backbone', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_empresa_cnpj', to='api.empresa')),
            ],
            options={
                'verbose_name': 'infraestrutura',
                'verbose_name_plural': 'infraestruturas',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_empresa_cnpj', to='api.empresa')),
                ('pessoa_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_pessoa_cpf', to='api.pessoa')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('banda', models.CharField(max_length=45)),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_empresa_cnpj', to='api.empresa')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_plano', models.CharField(max_length=45)),
                ('sla', models.CharField(max_length=45)),
                ('preco', models.IntegerField()),
                ('empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_empresa_cnpj', to='api.empresa')),
                ('plano_empresa_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_plano_empresa_cnpj', to='api.plano')),
                ('plano_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_plano_id', to='api.plano')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_setor_id', to='api.setor'),
        ),
    ]
